In [1]:
import torch

In [43]:
X = torch.tensor(
    [
        [0,0],
        [0,1], 
        [1,0], 
        [1,1]
    ],  dtype = torch.float 
)
Y = torch.tensor(
    [
        [0],
        [1],
        [1],
        [0]
    ],  dtype = torch.float
)
print(X.shape, Y.shape)

torch.Size([4, 2]) torch.Size([4, 1])


In [117]:
class XORNet(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.layer_1 = torch.nn.Linear(2, 2)
        self.non_li1 = torch.nn.LeakyReLU(negative_slope = 0.1)
        self.layer_2 = torch.nn.Linear(2, 1)
        self.print_mode = False
    
    def print_out(self, x : torch.Tensor):
        if self.print_mode:
            print(x)

    def forward(self, x : torch.Tensor) -> torch.Tensor:
        x = self.layer_1(x)
        self.print_out(x)
        x = self.non_li1(x)
        self.print_out(x)
        x = self.layer_2(x)
        self.print_out(x)
        return x

In [118]:
model = XORNet()
lossF = torch.nn.MSELoss()
optim = torch.optim.Adam(model.parameters(), lr = 0.01)

In [119]:
for i in range(1_000):
    xi = torch.unsqueeze(X, dim = 0)
    yi = torch.unsqueeze(Y, dim = 0)

    optim.zero_grad()
    yp = model(xi)
    ls = lossF(yp, yi)
    ls.backward()
    optim.step()
    
    if i % 100 == 0:
        print(i, ls.item())

0 0.5029937028884888
100 0.19782386720180511
200 0.16322200000286102
300 0.04640532284975052
400 0.0013145976699888706
500 6.598742402275093e-06
600 7.639002319592691e-09
700 1.3535839116229909e-12
800 2.957634137601417e-13
900 3.064215547965432e-13


In [120]:
model.print_mode = True

In [121]:
model(torch.tensor([[[1, 1]]], dtype = torch.float))

tensor([[[1.0231e+00, 2.7908e-08]]], grad_fn=<ViewBackward0>)
tensor([[[1.0231e+00, 2.7908e-08]]], grad_fn=<LeakyReluBackward0>)
tensor([[[1.1921e-07]]], grad_fn=<ViewBackward0>)


tensor([[[1.1921e-07]]], grad_fn=<ViewBackward0>)

In [122]:
model(torch.tensor([[[0, 1]]], dtype = torch.float))

tensor([[[2.0461, 1.0959]]], grad_fn=<ViewBackward0>)
tensor([[[2.0461, 1.0959]]], grad_fn=<LeakyReluBackward0>)
tensor([[[1.0000]]], grad_fn=<ViewBackward0>)


tensor([[[1.0000]]], grad_fn=<ViewBackward0>)

In [123]:
model(torch.tensor([[[0, 0]]], dtype = torch.float))

tensor([[[ 1.0231e+00, -9.1301e-08]]], grad_fn=<ViewBackward0>)
tensor([[[ 1.0231e+00, -9.1301e-09]]], grad_fn=<LeakyReluBackward0>)
tensor([[[3.5763e-07]]], grad_fn=<ViewBackward0>)


tensor([[[3.5763e-07]]], grad_fn=<ViewBackward0>)

In [124]:
model(torch.tensor([[[1, 0]]], dtype = torch.float))


tensor([[[ 0.0000, -1.0959]]], grad_fn=<ViewBackward0>)
tensor([[[ 0.0000, -0.1096]]], grad_fn=<LeakyReluBackward0>)
tensor([[[1.0000]]], grad_fn=<ViewBackward0>)


tensor([[[1.0000]]], grad_fn=<ViewBackward0>)

In [125]:
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name)
        print(param.data)
        print()

layer_1.weight
tensor([[-1.0231,  1.0231],
        [-1.0959,  1.0959]])

layer_1.bias
tensor([ 1.0231e+00, -9.1301e-08])

layer_2.weight
tensor([[-1.1947,  2.0277]])

layer_2.bias
tensor([1.2222])

